name: ai_exam_prep
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mysql_client: ^0.0.27
  firebase_core: ^2.13.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.1.0
  file_selector: ^0.9.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.1.4
  otp_pin_field: ^1.2.2
  url_launcher: ^6.1.8
  pdf: ^3.6.0
  flutter_pdf_text: ^0.9.0
  http: ^1.2.1
  path_provider: ^2.1.5
  dio: ^5.0.0
  pdfx: ^2.6.0
  flutter_dotenv: ^5.1.0
  google_generative_ai: ^0.2.0
  permission_handler: ^11.3.1
  open_filex: ^4.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
